### PR TITLE
fix refresh targets for json files

### LINKED ISSUE #527: Refresh targets ignores .atom-build.json
When I add a new target to my .atom-build.json and then do "Packages -> Build -> refresh targets" the new target does not appear in the list of available targets. I have to restart atom to have those changes reflected. Same for removing a target or updating its cmd

### PR DESCRIPTION
**Pull request by wiggisser**
seems require(filename) does not reread a changed json  file
fixes #527

### CODE REVIEW

**Comment by noseglid** [comment]
I guess the issue would still remain for a `js` file though.

**Comment by wiggisser** [comment]
I set a breakpoint directly before deleting from require.cache. At this breakpoint I see the following

1) When I load a project, `require.cache[realFile]` is undefined (as expected)
2) When I change the .atom-build.json file `require.cache[realFile]` contains the old configuration (as expected)
3) When I change the .atom-build.json file again `require.cache[realFile]` is undefined (not as expected)

It seems, that after the first time, the config is deleted from the require.cache, it is never added again, and all calls to require return the initial configuration, like it was when the file was read for the first time.

**Comment by noseglid** [comment]
Did you do these tests with or without the fix this PR suggests?

**Comment by wiggisser** [comment]
Without the PR, ie I did a `require(realFile)` also for json files

**Comment by wiggisser** [comment]
I did a bit more of debugging and tried to step into the `require` call. Seems that atom/electron has some custom implementation of the require call and a separate module cache which seems not to be affected by `delete require.cache[...]`. Thus, require is always returning the module from that custom module cache

**Comment by wiggisser** [comment]
I filed an issue with atom (https://github.com/atom/atom/issues/16435) regarding this, they closed it with "won't fix", so I guess using plain `require` won't work for updating the build configuration.

I think I found a more general solution, but as I already deleted my fork of this repo I can't update the pull request, so I'm clsoing it and creating a new one ...

**Comment by noseglid** [comment]
That's unfortunate, but at least we know why (and why I have to restart Atom for every package upgrade!).

**Pull request closed without merging**
