### PR TITLE
Convert platform-specific path delimiters to native platform delimiters.

### PR DESCRIPTION
**Pull request by Talon1024**
Use a more elegant method of passing `exec` and its arguments to child_process.spawn()

Also:
- Convert Windows path delimiters to Unix path delimiters on Unix platforms.
- Convert Unix path delimiters to Windows path delimiters on Windows platforms.

### CODE REVIEW

**Comment by noseglid** [comment]
Could you also add a test for this? It's been broken a few times already.

**Comment by Talon1024** [comment]
I'm still working on this.

**Comment by Talon1024** [comment]
I've decided to change this and just use a more elegant way of passing the `exec` and `args` to the child process.

Judging by the way you've wrote your unit tests, the `sh` option is only supposed to be true if the `cmd` string is a series of bash/shell commands, and not the name of a build script or build command.

**Comment by noseglid** [comment]
Well.. if `sh` is true. The command will be spawned with a shell (e.g. `bash` or `cmd.exe`.) If it is false the OS will directly [exec](http://www.freebsd.org/cgi/man.cgi?query=exec&sektion=3) the command.

Exec has a limitation in that it doesn't support arguments "in the command". Other than that either is fine.

I tend to avoid `sh` because it feels faster to not start a shell and then spawn the command in there - but I don't think it has any noticeable impact on execution time in most cases.

**Comment by noseglid** [comment]
Closing as inactive. Please open a new PR if you intend to keep working on this.

**Pull request closed without merging**
