### PR TITLE
Fix spelling: succeding -> succeeding

### PR DESCRIPTION
**Pull request by 0xdec**
I searched through several build providers to see if this would break anything, and I haven't yet found any uses of this hook, but this needs more extensive searching to be sure.

### CODE REVIEW

**Comment by noseglid** [comment]
I think @ivankravets is using it. Am I wrong?

**Comment by ivankravets** [comment]
We use preBuild/postBuild hooks. See https://github.com/platformio/platformio-atom-ide/blob/develop/lib/services/build.js#L258

**Comment by 0xdec** [comment]
I just searched through every repository in the list of [build providers](https://atombuild.github.io/) and couldn't find anyone using it. The only place I found it on GitHub was in many users atom configuration repos (dotfiles), which shouldn't matter.

**Comment by noseglid** [comment]
This just changes the specs and an obvious spelling error.
Would you mind rebasing on latest `master` where I've fixed the specs?

**Comment by noseglid** [comment]
Thanks!

**Pull request merged**
