### PR TITLE
add support for scons

### PR DESCRIPTION
**Pull request by carneeki**
add support for scons

### CODE REVIEW

**Comment by noseglid** [comment]
Cool. Would you mind adding a test for SCons as well?

**Comment by carneeki** [comment]
I'm not 100% familiar with the test environment and I got about halfway through before I thought I should ask for advice.

I've written a few SConstruct files based on the Makefiles provided, and I started modifying ```/spec/build-spec.js``` but I'm not sure I'm on the right track. Is build-spec.js automatically generated?

Also... Ideally, I need to run scons with a few extra flags compared to normal:
```scons -sc distclean -f SConstruct.escape```

This is because scons generates a checksum file, and ideally it would be nice to clean that up after each test.

What are your thoughts?

**Comment by noseglid** [comment]
It looks good! `build-spec.js` is not automatically generated, so what you're doing is the right thing.

It appears as the `SConstruct.escape` file (and the defined variable) is never used. Should it be removed?

Each test is run in a new clean directory which is removed after the test is done. Are the checksum files kept in a global state or would they be removed along with the directory?

**Comment by carneeki** [comment]
Cool thanks for the advice :)

I hadn't got around to using ``` SConstruct.escape``` yet. I'll keep
working on it.

The checksum files are OK to let the framework remove. I just thought I had
to tidy up after myself, but if the framework does it, that's even better.

Thanks Alexander!

On 9 April 2015 at 15:57, Alexander Olsson <notifications@github.com> wrote:

> It looks good! build-spec.js is not automatically generated, so what
> you're doing is the right thing.
>
> It appears as the SConstruct.escape file (and the defined variable) is
> never used. Should it be removed?
>
> Each test is run in a new clean directory which is removed after the test
> is done. Are the checksum files kept in a global state or would they be
> removed along with the directory?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noseglid/atom-build/pull/54#issuecomment-91123171>.
>



-- 
Adam "carneeki" Carmichael
p: +61 415 37 1990
w: http://bigneek.com
e: carneeki@carneeki.net
i: 2207644

**Comment by noseglid** [comment]
Any updates on this?

**Comment by noseglid** [comment]
Closing this out. Please re-open if you wish to finish this PR.

**Pull request closed without merging**
