### PR TITLE
Update atom-build.js

### PR DESCRIPTION
**Pull request by C-Bouthoorn**
Fixed problem where Atom would crash on Linux.

As discussed [here](https://github.com/noseglid/atom-build/issues/277)

### CODE REVIEW

**Comment by noseglid** [comment]
It appears it returns a `StatWatcher` instead, which does not have a close function. It is an event emitter so you must call `removeAllListeners()` instead.

**Comment by noseglid** [comment]
@C-Bouthoorn ping on this :)

**Comment by C-Bouthoorn** [comment]
Oh, whoops, good that you ping. Will fix!

**Comment by C-Bouthoorn** [comment]
Okay, so Travis doesn't like it, but is this problem related to this?

**Comment by noseglid** [comment]
No I think they are related. One is about cached content of atom-build. Which the file watchers are in charge of not doing. I tried re-triggering the test and it fails with same error. I also get those errors locally.

**Comment by C-Bouthoorn** [comment]
Okay, so it's clear that it doesn't work. However, I have no idea how I should fix this. It looks like `.watchFile()` just caches the file, and that that can't be changed. I don't have any idea why the timeout happens either. I'm sorry

**Comment by noseglid** [comment]
Too bad.. this was circumstantial at best anyway. I think we should attempt to get to the root cause of the crash rather than this work around. I'll close this PR.

**Pull request closed without merging**
