### PR TITLE
Optionally override theme with terminal style

### LINKED ISSUE #338: Doesn't pick a theme
Colors in a build result are always black. Changing a theme doesn't affect the colors.

screenshot 2016-03-12 14 08 46

Environment:
- Atom 1.5.4
- OS X 10.11.3
- build 0.56.0 (the bug exists since this version)

### PR DESCRIPTION
**Pull request by noseglid**
Terminal works "best" under black background and white
text. However this may not look very good with light theme,
or other dark themes. Allow user to opt out of overriden
colors.

Fixes #338

### CODE REVIEW

**Comment by nixpulvis** [comment]
Missing the left border when I tried it.

screen shot 2016-03-15 at 2 25 37 am

**Comment by noseglid** [comment]
As you can see, there's no border on the status panel either. I'm not sure whether it's really the responsibility of this package to put borders on the panel. The panel is a built in Atom component which a theme can modify. Which theme are you using. Maybe you can open an issue there?

Optionally you could add this to your stylesheet:
```
atom-panel {
  border-left: solid 1px @tool-panel-border-color;
}
```

**Comment by nixpulvis** [comment]
This is just the One Light theme, I'm not really sure what should be considered a panel or not. But this is the only package I have doing this at the moment, granted I don't have other packages that pop up in the same place.

**Comment by noseglid** [comment]
I see. I do not know the reasoning behind not having borders on panels. I admit it does look **too** integrated with the tree view.

**Comment by noseglid** [comment]
From what I can tell it's the `One` theme's that have this issue. `Atom Dark` and `Atom Light` sets a border on the tree view resulting in expected visuals:
screen shot 2016-03-15 at 08 52 36

I'd say it's definitely an "issue" (or design choice, who knows) with the `One` themes.

**Comment by nixpulvis** [comment]
I'll open an issue in that theme and see what they say.

**Comment by noseglid** [comment]
I'd be happy to chime in if you post the link to the issue!

**Pull request merged**
