### PR TITLE
Use a service instead of hard-coding all the tools.

### PR DESCRIPTION
**Pull request by bwinton**
It ended up being pretty easy to use a Service-based architecture, and I had some free time, so I did this.  :smile:

See https://github.com/bwinton/atom-build-jpm or https://github.com/bwinton/atom-build-markdown for example service providers.

### CODE REVIEW

**Comment by noseglid** [comment]
Not bad! I will have a look at it as soon as I have some time over!

**Comment by noseglid** [comment]
I'm curious. Why did you choose to have `atom-build` consume a service which is provided by the different packages? Would it be more natural the other way around?

**Comment by bwinton** [comment]
It's a good question.  Mostly I was basing it off the [AtomLinter](https://github.com/AtomLinter/Linter/blob/master/package.json#L15) code, which does things this way.  My other thought was that since atom-build is the thing that's in control, calling the other packages, it's kind of using their linting services, but that's really more of an after-the-fact justification than a reason…  The other main reason is that it seemed to work this way, so I didn't bother trying to get it working the other way.  :wink:

**Comment by bwinton** [comment]
(One thing I just noticed is that `consumeBuilder` will need to return a `Disposable` that removes the builders from `extra_tools`, so that we don't try to use them when someone disables or uninstalls the extra packages…  I'm not sure how that would work if atom-build was providing the service.)

**Comment by noseglid** [comment]
After looking at how the Linter does it, it seems best to have it this way.

I think we should fix the `Disposable` thing as well. It seems fairly easy, but we need to assign an `id` in the extra_tools array (making it an object) so we can remove it.

Also, how should a build tool (e.g. your markdown plugin) react if `atom-build` is removed? Would it even get notified?

**Comment by noseglid** [comment]
I ported the `gulp` tool to a [repository of its own](https://github.com/noseglid/atom-build-gulp) as well. Works really well and is an excellent modularization of atom-build!

**Comment by bwinton** [comment]
(Just as a note, I'll probably get to this tomorrow afternoon, or sometime Saturday, if you don't fix it first.)

**Comment by bwinton** [comment]
> I think we should fix the Disposable thing as well. It seems fairly easy, but we need to assign an id in the extra_tools array (making it an object) so we can remove it.

Fixed.  Since I believe the objects will be unique, I'm just using lodash to remove them (and I switched to using lodash to add them, for consistency).

> Also, how should a build tool (e.g. your markdown plugin) react if atom-build is removed? Would it even get notified?

It doesn't get any notifications, but it never gets called, so it all works out.  (It will get re-registered when `atom-build` is re-installed, and magically start working. :smile: )

**Comment by noseglid** [comment]
This is great! Thank you for this!

**Comment by bwinton** [comment]
You're very welcome.  And thank you for making atom-build` in the first place, so I didn't have to!

**Pull request merged**
