### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tcyrus**
Add `<kbd>` tags and added JSON syntax highlighting to code block

### CODE REVIEW

**Comment by noseglid** [comment]
Cool thanks.

I think it looks nice to have the dashes inside the `kbd` like this:
screen shot 2016-04-08 at 08 31 47

Possibly remove the dashes, but keep the keys separate.

**Comment by tcyrus** [comment]
@noseglid, I amended the commit

**Comment by noseglid** [comment]
I don't see any changes from the first commit.

Pro tip: Don't amend the commit, simply push a new commit and history can be followed.

**Comment by C-Bouthoorn** [comment]
This error is in no way related to this PR. I think it's safe to pull

**Comment by noseglid** [comment]
Cool, thanks mate!

**Pull request merged**
