### PR TITLE
[Bugfix] Fixes links not showing up

### PR DESCRIPTION
**Pull request by MackieLoeffel**
Fixes highlighting of some errors and maybe #201.

### CODE REVIEW

**Comment by noseglid** [comment]
What does the output look like that fixes this?

**Comment by MackieLoeffel** [comment]
Something with characters, which are escaped by `_.escape`, like `<` or `>`
`at Object.<anonymous> (C:\\coding\\buildtest.coffee:2:10)`

**Comment by noseglid** [comment]
So um... consider this output: `some stuff <match>`
Using the regex: `<match>` (if that was the errorMatch).

now it would be escaped so that it would look for `&lt;match&gt` in the string `some stuff <match>` which wouldn't hit.

Why doesn't it work as is?

**Comment by MackieLoeffel** [comment]
The string, in which the links are inserted, is escaped as well beforehand. So the string is `some stuff &lt;match&gt;`
https://github.com/noseglid/atom-build/blob/ed6f0a5860cedc48875c36c86431ca217064fb72/lib/build-view.js#L231

you can't escape the string afterwards, because then you would escape the inserted `<a>` tags as well.

**Comment by xpol** [comment]
I can confirm that this fixes #201.

Here is my errorMatch:

```json
  "errorMatch":[
    "\\[string \\\"(?<file>[^\\\"]+)\\\"\\]:(?<line>\\d+)",
    "line (?<line>\\d+) of chunk '\\\"(?<file>[^\\\"]+)\\\""
  ]
```

Maybe because of `[`, `]` or `"` in regex.

**Comment by xpol** [comment]
Thanks @MackieLoeffel !

**Comment by noseglid** [comment]
Cool. I see! Great fix @MackieLoeffel.

**Pull request merged**
